name: Render Deploy

on:
    pull_request:
      branches:
        - main
      type:
        - closed

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
        - uses: action/checkout@v1

        - name: Test
          run: |
            npm install
            npm run test

        - name: Deploy
          if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"